// Curated Lucide registry. A generous, categorised subset of Lucide line icons
// surfaced in the IconPicker and resolvable by `<AppIcon icon="lucide:...">`.
// Token value == the `name` field (kebab-case). Keeping a curated set (rather
// than all ~1500 icons) keeps the bundle lean and the picker calm.

import {
  type LucideIcon,
  Server,
  Database,
  HardDrive,
  Cpu,
  MemoryStick,
  Container,
  Boxes,
  Box,
  Layers,
  Component,
  Workflow,
  Network,
  Globe,
  Wifi,
  Router,
  Cloud,
  CloudCog,
  Cable,
  Radio,
  Share2,
  Waypoints,
  Terminal,
  SquareTerminal,
  Code,
  CodeXml,
  Braces,
  Binary,
  Bug,
  GitBranch,
  FileCode,
  Command,
  Shield,
  ShieldCheck,
  ShieldAlert,
  Lock,
  LockKeyhole,
  Key,
  KeyRound,
  Fingerprint,
  UserCheck,
  Eye,
  ScanFace,
  Monitor,
  MonitorSmartphone,
  Smartphone,
  Laptop,
  Tablet,
  Tv,
  File,
  FileText,
  Folder,
  FolderTree,
  FolderOpen,
  Files,
  Archive,
  FileJson,
  FileCog,
  Activity,
  CircleCheck,
  TriangleAlert,
  CircleAlert,
  Info,
  CircleDot,
  Zap,
  Flame,
  Star,
  Heart,
  Bell,
  Bookmark,
  Flag,
  Sparkles,
  Building,
  Building2,
  House,
  MapPin,
  Map,
  Tag,
  Tags,
  Users,
  User,
  Briefcase,
  Wrench,
  Settings,
  Cog,
  Rocket,
  Beaker,
  FlaskConical,
  Gauge,
  Wand,
  Bot,
  BrainCircuit,
  Leaf,
  TreePine,
  Sprout,
  Mountain,
  Sun,
  Moon,
} from "lucide-react"

export interface LucideEntry {
  name: string
  Comp: LucideIcon
  category: string
  keywords?: string
}

export const LUCIDE_ICONS: LucideEntry[] = [
  // 通用 / 基础设施
  { name: "server", Comp: Server, category: "通用", keywords: "host machine 主机 服务器" },
  { name: "database", Comp: Database, category: "通用", keywords: "db 数据库 存储" },
  { name: "hard-drive", Comp: HardDrive, category: "通用", keywords: "disk 磁盘 存储" },
  { name: "cpu", Comp: Cpu, category: "通用", keywords: "处理器 芯片" },
  { name: "memory-stick", Comp: MemoryStick, category: "通用", keywords: "ram 内存" },
  { name: "container", Comp: Container, category: "通用", keywords: "容器 docker" },
  { name: "boxes", Comp: Boxes, category: "通用", keywords: "集群 cluster 资源" },
  { name: "box", Comp: Box, category: "通用", keywords: "包 package 资源" },
  { name: "layers", Comp: Layers, category: "通用", keywords: "分层 stack" },
  { name: "component", Comp: Component, category: "通用", keywords: "组件 模块" },
  { name: "workflow", Comp: Workflow, category: "通用", keywords: "流程 编排" },

  // 网络
  { name: "network", Comp: Network, category: "网络", keywords: "网络 拓扑 tcp" },
  { name: "globe", Comp: Globe, category: "网络", keywords: "全球 公网 internet" },
  { name: "wifi", Comp: Wifi, category: "网络", keywords: "无线 wlan" },
  { name: "router", Comp: Router, category: "网络", keywords: "路由 网关" },
  { name: "cloud", Comp: Cloud, category: "网络", keywords: "云 cloud" },
  { name: "cloud-cog", Comp: CloudCog, category: "网络", keywords: "云配置" },
  { name: "cable", Comp: Cable, category: "网络", keywords: "线缆 连接" },
  { name: "radio", Comp: Radio, category: "网络", keywords: "信号 广播" },
  { name: "share-2", Comp: Share2, category: "网络", keywords: "转发 分享 forward" },
  { name: "waypoints", Comp: Waypoints, category: "网络", keywords: "代理链 hops 跳转" },

  // 终端 / 开发
  { name: "terminal", Comp: Terminal, category: "终端", keywords: "shell ssh 命令行" },
  { name: "square-terminal", Comp: SquareTerminal, category: "终端", keywords: "console 终端" },
  { name: "code", Comp: Code, category: "终端", keywords: "代码 开发" },
  { name: "code-xml", Comp: CodeXml, category: "终端", keywords: "代码 xml" },
  { name: "braces", Comp: Braces, category: "终端", keywords: "json 配置" },
  { name: "binary", Comp: Binary, category: "终端", keywords: "二进制" },
  { name: "bug", Comp: Bug, category: "终端", keywords: "调试 bug" },
  { name: "git-branch", Comp: GitBranch, category: "终端", keywords: "git 分支" },
  { name: "file-code", Comp: FileCode, category: "终端", keywords: "脚本 代码文件" },
  { name: "command", Comp: Command, category: "终端", keywords: "命令" },

  // 安全
  { name: "shield", Comp: Shield, category: "安全", keywords: "防护 安全" },
  { name: "shield-check", Comp: ShieldCheck, category: "安全", keywords: "已审批 安全" },
  { name: "shield-alert", Comp: ShieldAlert, category: "安全", keywords: "风险 告警" },
  { name: "lock", Comp: Lock, category: "安全", keywords: "锁 加密" },
  { name: "lock-keyhole", Comp: LockKeyhole, category: "安全", keywords: "锁 密钥" },
  { name: "key", Comp: Key, category: "安全", keywords: "密钥 凭据" },
  { name: "key-round", Comp: KeyRound, category: "安全", keywords: "凭据 credential" },
  { name: "fingerprint", Comp: Fingerprint, category: "安全", keywords: "指纹 身份" },
  { name: "user-check", Comp: UserCheck, category: "安全", keywords: "认证 授权" },
  { name: "eye", Comp: Eye, category: "安全", keywords: "审计 监控" },
  { name: "scan-face", Comp: ScanFace, category: "安全", keywords: "人脸 mfa" },

  // 设备 / 显示
  { name: "monitor", Comp: Monitor, category: "设备", keywords: "桌面 rdp vnc 显示" },
  { name: "monitor-smartphone", Comp: MonitorSmartphone, category: "设备", keywords: "多端" },
  { name: "smartphone", Comp: Smartphone, category: "设备", keywords: "手机 移动" },
  { name: "laptop", Comp: Laptop, category: "设备", keywords: "笔记本" },
  { name: "tablet", Comp: Tablet, category: "设备", keywords: "平板" },
  { name: "tv", Comp: Tv, category: "设备", keywords: "屏幕 display" },

  // 文件
  { name: "file", Comp: File, category: "文件", keywords: "文件" },
  { name: "file-text", Comp: FileText, category: "文件", keywords: "文档 文本" },
  { name: "folder", Comp: Folder, category: "文件", keywords: "目录 文件夹" },
  { name: "folder-tree", Comp: FolderTree, category: "文件", keywords: "目录树 sftp" },
  { name: "folder-open", Comp: FolderOpen, category: "文件", keywords: "打开目录" },
  { name: "files", Comp: Files, category: "文件", keywords: "多文件" },
  { name: "archive", Comp: Archive, category: "文件", keywords: "归档 压缩" },
  { name: "file-json", Comp: FileJson, category: "文件", keywords: "json 配置" },
  { name: "file-cog", Comp: FileCog, category: "文件", keywords: "配置文件" },

  // 状态 / 强调
  { name: "activity", Comp: Activity, category: "状态", keywords: "活动 会话 监控" },
  { name: "circle-check", Comp: CircleCheck, category: "状态", keywords: "完成 成功" },
  { name: "triangle-alert", Comp: TriangleAlert, category: "状态", keywords: "警告 风险" },
  { name: "circle-alert", Comp: CircleAlert, category: "状态", keywords: "错误 警示" },
  { name: "info", Comp: Info, category: "状态", keywords: "信息 提示" },
  { name: "circle-dot", Comp: CircleDot, category: "状态", keywords: "状态点" },
  { name: "zap", Comp: Zap, category: "状态", keywords: "快速 闪电 工具" },
  { name: "flame", Comp: Flame, category: "状态", keywords: "热点 火" },
  { name: "star", Comp: Star, category: "状态", keywords: "收藏 重要" },
  { name: "heart", Comp: Heart, category: "状态", keywords: "喜欢 收藏" },
  { name: "bell", Comp: Bell, category: "状态", keywords: "通知 提醒" },
  { name: "bookmark", Comp: Bookmark, category: "状态", keywords: "书签 标记" },
  { name: "flag", Comp: Flag, category: "状态", keywords: "旗标 标记" },
  { name: "sparkles", Comp: Sparkles, category: "状态", keywords: "ai 智能 闪" },

  // 业务 / 对象
  { name: "building", Comp: Building, category: "业务", keywords: "公司 机房" },
  { name: "building-2", Comp: Building2, category: "业务", keywords: "组织 部门" },
  { name: "house", Comp: House, category: "业务", keywords: "首页 home" },
  { name: "map-pin", Comp: MapPin, category: "业务", keywords: "区域 位置 region" },
  { name: "map", Comp: Map, category: "业务", keywords: "地图 拓扑" },
  { name: "tag", Comp: Tag, category: "业务", keywords: "标签" },
  { name: "tags", Comp: Tags, category: "业务", keywords: "标签 分组" },
  { name: "users", Comp: Users, category: "业务", keywords: "团队 用户组" },
  { name: "user", Comp: User, category: "业务", keywords: "用户 账号" },
  { name: "briefcase", Comp: Briefcase, category: "业务", keywords: "项目 工作" },
  { name: "wrench", Comp: Wrench, category: "业务", keywords: "工具 维护" },
  { name: "settings", Comp: Settings, category: "业务", keywords: "设置 配置" },
  { name: "cog", Comp: Cog, category: "业务", keywords: "齿轮 配置" },
  { name: "rocket", Comp: Rocket, category: "业务", keywords: "上线 发布 prod" },
  { name: "beaker", Comp: Beaker, category: "业务", keywords: "测试 实验 test" },
  { name: "flask-conical", Comp: FlaskConical, category: "业务", keywords: "实验 staging" },
  { name: "gauge", Comp: Gauge, category: "业务", keywords: "性能 仪表" },
  { name: "wand", Comp: Wand, category: "业务", keywords: "魔法 ai 自动" },
  { name: "bot", Comp: Bot, category: "业务", keywords: "机器人 agent ai" },
  { name: "brain-circuit", Comp: BrainCircuit, category: "业务", keywords: "ai 智能 大脑" },

  // 自然 / 主题
  { name: "leaf", Comp: Leaf, category: "自然", keywords: "环保 绿色" },
  { name: "tree-pine", Comp: TreePine, category: "自然", keywords: "树 森林" },
  { name: "sprout", Comp: Sprout, category: "自然", keywords: "新生 dev" },
  { name: "mountain", Comp: Mountain, category: "自然", keywords: "山 峰" },
  { name: "sun", Comp: Sun, category: "自然", keywords: "白天 亮" },
  { name: "moon", Comp: Moon, category: "自然", keywords: "夜间 暗" },
]

export const LUCIDE_MAP: Record<string, LucideIcon> = Object.fromEntries(
  LUCIDE_ICONS.map((e) => [e.name, e.Comp]),
)

export const LUCIDE_CATEGORIES = Array.from(new Set(LUCIDE_ICONS.map((e) => e.category)))
