package desktop

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/google/uuid"
)

// devolutionsGatewayConfig mirrors the subset of fields the Devolutions
// Gateway accepts in its `devolutions-gateway.json`. Only the fields we
// actually set are present; the gateway tolerates extra/missing keys
// with documented defaults. See:
//   https://github.com/Devolutions/devolutions-gateway/blob/master/docs/COOKBOOK.md
//
// Fields use the gateway's exact PascalCase JSON names, not Go camelCase.
type devolutionsGatewayConfig struct {
	ID                       string            `json:"Id"`
	Hostname                 string            `json:"Hostname,omitempty"`
	ProvisionerPublicKeyFile string            `json:"ProvisionerPublicKeyFile"`
	Listeners                []devGwListener   `json:"Listeners"`
	Verbosity                string            `json:"Verbosity,omitempty"`
	LogDirective             string            `json:"LogDirective,omitempty"`
	Sogar                    *devGwSogar       `json:"Sogar,omitempty"`
}

type devGwListener struct {
	InternalUrl string `json:"InternalUrl"`
	ExternalUrl string `json:"ExternalUrl,omitempty"`
}

// devGwSogar reserved for future session recording integration; left
// nil in the current scope so the gateway doesn't try to upload.
type devGwSogar struct {
	RegistryUrl  string `json:"RegistryUrl,omitempty"`
	Username     string `json:"Username,omitempty"`
	PasswordFile string `json:"PasswordFile,omitempty"`
}

// gatewayConfigInputs are the values our supervisor knows; the rest
// of the on-disk config is generated by WriteGatewayConfig from them.
type gatewayConfigInputs struct {
	ConfigPath    string // e.g. /var/lib/jumpserver/devolutions-gateway/gateway.json
	PublicKeyPath string // path to the .pub PEM file from JWTSigner
	ListenURL     string // e.g. http://127.0.0.1:7171
	Hostname      string // e.g. "jumpserver-anonymous"
	IDFile        string // where to persist the gateway's stable Id (uuid)
	Verbosity     string // "warn" | "info" | "debug" — passed straight to gateway
}

// WriteGatewayConfig (re)generates the Devolutions Gateway JSON config
// to match our current state. Called every time we start the subprocess
// so config drift can't accumulate across restarts.
//
// The gateway Id is persisted to a sidecar file (IDFile) so it stays
// stable across restarts — Devolutions Gateway uses the Id for log
// correlation and external dashboards, and a fresh uuid every start
// would scramble those.
func writeGatewayConfig(in gatewayConfigInputs) error {
	if in.ConfigPath == "" {
		return fmt.Errorf("gateway_config: ConfigPath required")
	}
	if in.PublicKeyPath == "" {
		return fmt.Errorf("gateway_config: PublicKeyPath required")
	}
	if in.ListenURL == "" {
		in.ListenURL = "http://127.0.0.1:7171"
	}
	if in.Verbosity == "" {
		in.Verbosity = "info"
	}
	id, err := loadOrMintGatewayID(in.IDFile)
	if err != nil {
		return err
	}
	cfg := devolutionsGatewayConfig{
		ID:                       id,
		Hostname:                 in.Hostname,
		ProvisionerPublicKeyFile: in.PublicKeyPath,
		Verbosity:                in.Verbosity,
		Listeners: []devGwListener{
			{InternalUrl: in.ListenURL},
		},
	}
	body, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return fmt.Errorf("gateway_config: marshal: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(in.ConfigPath), 0o700); err != nil {
		return fmt.Errorf("gateway_config: mkdir %s: %w", filepath.Dir(in.ConfigPath), err)
	}
	if err := os.WriteFile(in.ConfigPath, body, 0o600); err != nil {
		return fmt.Errorf("gateway_config: write %s: %w", in.ConfigPath, err)
	}
	return nil
}

func loadOrMintGatewayID(path string) (string, error) {
	if path == "" {
		// No sidecar — mint an ephemeral one. Log correlation across
		// restarts will be lost, but the gateway still functions.
		return uuid.NewString(), nil
	}
	buf, err := os.ReadFile(path)
	if err == nil {
		id := string(buf)
		// Trim newline-style noise; keep the rest verbatim.
		for len(id) > 0 && (id[len(id)-1] == '\n' || id[len(id)-1] == '\r' || id[len(id)-1] == ' ') {
			id = id[:len(id)-1]
		}
		if _, perr := uuid.Parse(id); perr == nil {
			return id, nil
		}
		// File exists but doesn't contain a uuid; mint a fresh one and
		// overwrite so future starts read the same Id.
	}
	if !os.IsNotExist(err) && err != nil {
		// Read failure other than not-exist — surface so the operator
		// can fix permissions instead of silently rotating Ids.
		if !os.IsNotExist(err) {
			return "", fmt.Errorf("gateway_config: read %s: %w", path, err)
		}
	}
	id := uuid.NewString()
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return "", fmt.Errorf("gateway_config: mkdir %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(id), 0o600); err != nil {
		return "", fmt.Errorf("gateway_config: write %s: %w", path, err)
	}
	return id, nil
}
